on:
  push:
    branches: [main]
  pull_request:
      branches: [main]

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🔨 Build Project
      run: |
        composer install --no-scripts
        cd wp-content/themes/startdigital
        npm install
        npm run build
        composer install

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.perth.agency
        username: perthage
        password: ${{ secrets.DEV_FTP_PASS }}
        server-dir: SITENAME/
        protocol: ftps
